name: "Periodic Work"

on:
  workflow_dispatch:

jobs:
  do-work:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      NO_PAGER: "true"
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main
      - name: Get latest release or pre release
        id: check_prev_release
        run: |          
          raw_latest_release=$(gh release list --limit 5 --json tagName,isDraft --jq 'map(select(.isDraft | not)) | .[0].tagName' | xargs)
        
          if [[ -z "$raw_latest_release" ]]; then
            echo "Error: Could not determine the latest release."
            exit 1
          fi
          # Drop the first character ('v') from the release tag
          latest_release=${raw_latest_release#v}
          
          # Check if the grep command found anything
          merge_commit_log=$(git log main --merges --oneline | grep $latest_release || true)
          
          if [[ -n "$merge_commit_log" ]]; then
            echo "Found merge commit for release $latest_release:"
            echo "$merge_commit_log"
            echo "has_previous_release_completed=true" >> "$GITHUB_OUTPUT"
          else
            echo "No merge commit found for release $latest_release on develop."
            echo "has_previous_release_completed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Do work
        # This step will only execute if the 'has_previous_release_completed' output from the 'check_prev_release' step was 'true'
        if: steps.check_prev_release.outputs.has_previous_release_completed == 'true'
        run: |
          echo "Success! The latest release has been merged into the main branch."
          echo "Sleeping for 1 minute"
          sleep 60

      - name: This step runs ONLY if the release was NOT merged
        # This is an optional step to provide clear feedback in the opposite case
        if: steps.check_prev_release.outputs.has_previous_release_completed == 'false'
        run: |
          echo "Action required: The latest release has not been merged into the main branch yet."
